name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Migrate Database
      run: php artisan migrate
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        APP_KEY: base64:k7iTOShVeNEaf4ndHK56nBepoUv3ScROq/aDNR/kyfU=
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
    - name: Run dusk tests
      run: |
        php artisan dusk:chrome-driver
        ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
        php artisan serve > /dev/null 2>&1 &
        php artisan dusk
